root: '123456'
bt_uin: '123456789'
debug: false
github_proxy: null
check_ncatbot_update: true
skip_ncatbot_install_check: false
websocket_timeout: 15
napcat:
  ws_uri: ws://localhost:16708
  ws_token: napcat_ws
  ws_listen_ip: localhost
  webui_uri: http://localhost:6099
  webui_token: (7Pyst9=}RO^^=|b
  enable_webui: true
  enable_update_check: false
  stop_napcat: false
  remote_mode: false
  report_self_message: false
  report_forward_message_detail: true
plugin:
  plugins_dir: plugins
  plugin_whitelist: []
  plugin_blacklist: []
  load_plugin: true
